# Generated by Django 3.2.18 on 2023-05-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postscategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
