# Generated by Django 3.2.18 on 2023-05-31 12:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postscategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field='image', max_length=18, null=True, samples=None),
        ),
    ]
