# Generated by Django 3.2.18 on 2023-06-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='phone_number',
            field=models.CharField(max_length=32),
        ),
    ]
