# Generated by Django 3.2.18 on 2023-06-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20230602_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
