# Generated by Django 3.2.18 on 2023-05-30 09:18

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to=userprofile.models.upload_user_avatar_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
